filter:
    excluded_paths:
        - app/tests/*
        - app/views/*
        - app/config/*
        - app/database/*
tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_cs_fixer:
        filter:
            paths:
                - app/TypiCMS/*
            excluded_paths:
                - app/TypiCMS/Modules/*/Views/*
        config:
            level: psr2
            fixers:
                indentation:          true
                linefeed:             true
                trailing_spaces:      true
                unused_use:           true
                phpdoc_params:        true
                visibility:           true
                return:               true
                short_tag:            true
                braces:               true
                include:              true
                php_closing_tag:      true
                extra_empty_lines:    true
                controls_spaces:      true
                elseif:               true
                eof_ending:           true
